import type { Metadata } from "next";
import Header from "@/components/Header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/styles/app.scss'; // 引入全域 SCSS 文件
import '@/styles/style.scss'; // 如果需要另一個全域樣式
import ToastProvider from '@/components/ToastProvider';
import { AuthProvider } from '@/context/AuthContext';

// 加載 Google 字體
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata 設置
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根佈局
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider />
        <Header />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
